title: Proyectos de Cómic - Dani
description: Ilustrador profesional con experiencia en cómic y diseño de personajes.
baseurl: "" # Si está alojado como usuario.github.io, déjalo vacío
url: "https://danifromdani.github.io"
theme: minima
